# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 想猫的鱼
brief-intro: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xmdySA.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links

github_username:  xmdySA
email: 852689344@.com
wangyiyun_username: 想猫的鱼SA


description_footer: 本站记录汾酒新闻和其他小玩意！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name

gitalk: 
    enable: true
    owner: xmdySA
    repo: https://xmdysa.github.io
    clientID: 224a9f50962035a7c07a
    clientSecret: f5f0089452fc4b9b55ee94598f5e4c8009dd6096
    admin: xmdySA

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
